### PR TITLE
it's possible to add svn revisions while cloning

### PR DESCRIPTION
**Pull request by ghost**
"Sadly, there's no way to add this to the git clone command." is not correct, document updated accordingly.  I learned that from https://wiki.freebsd.org/GitWorkflow originally, showing the git clone example adding svn revisions.  Note that _$ cd freebsd && git pull   # For some reason, the notes will not be fetched during the clone operation ..._ part is no longer true (at least for our repository), so it's not included.

### CODE REVIEW

**Comment by bsdimp** [comment]
Is there a minimum version needed for this? I'd read online that this command didn't work...

**Comment by bsdimp** [comment]
And thanks

**Comment by ghost** [comment]
> Is there a minimum version needed for this? I'd read online that this command didn't work...

The -c/--config is there from 2011; "not working" I'm not sure about, possibly the note about additional `git pull` applies to older versions.  At least current one in the ports tree (2.25.0) does work.

**Review by bsdimp — COMMENTED** [review]
Looks like this works on most recent versions...

**Pull request merged**
