### PR TITLE
Suggest symlinks for the commit message hook

### PR DESCRIPTION
**Pull request by arichardson**

### CODE REVIEW

**Comment by emaste** [comment]
I didn't suggest a symlink as it may be easy to inadvertently run 3rd party code.

**Comment by arichardson** [comment]
> I didn't suggest a symlink as it may be easy to inadvertently run 3rd party code.

I guess it could cause issues if someone commits a (malicious) change to the commit hook, but if that happens you could also be unlucky with the timing of the download.

**Comment by emaste** [comment]
It's more likely that folks will checkout some branch of unknown provenance though (to review a submission etc.)

**Comment by arichardson** [comment]
I didn't consider that, I guess we can revert this? I was just assuming that the commit message template might change, so a symlink would automatically get those updates. But if we are happy with the current template that's fine.

**Comment by bsdimp** [comment]
I hadn't considered the 'unknown branch' issue...

**Pull request merged**
